### ISSUE TITLE
Support for DS4Vita

### ISSUE THREAD

**Issue by Codemonkey03** [CallmeBK/VolLightbarCtrlWithDS4#1]
Any possibility of support with just the DS4Vita plugin instead of MinivitaTV? Using with just DS4Vita plugin almost works; volume up and down seem to function. Mute does not and the DS4 light bar doesn't change colors.

**Comment by CallmeBK** [comment]
Actually DS4Vita doesn't support the lightbar at all. In order for it to
work, DS4Vita would have to be updated to enable the lightbar and honestly
I don't know enough yet to figure that out. I'm pretty sure it's possible
though.

As for the mute thing, did you try holding select+L1+R1 for a few seconds?
I know that it isn't instant like when you want to just increase or
decrease the volume.

**Comment by CallmeBK** [comment]
Out of curiosity, why do you use DS4Vita instead of MinivitaTV?

**Comment by Codemonkey03** [comment]
One reason and it's gonna sound a little silly. When MiniVitaTV is active whenever the Vita is put to sleep and you wake it up it always has a big notice in the corner that says "Press the PS Button" and I don't like it. I spend 20% of my Vita time using a DS4, so that means the other 80% is spent using it on the go where I don't have a DS4 in sight so getting that warning every single time I put the Vita to sleep and wake it up several dozen times in a day annoys the hell out of mine.

If I could disable that message, I would switch from DS4Vita to MiniVitaTV easily.

Also MiniVitaTV doesn't support using the DS4 touch pad for the Vita touch screen, which is important for a lot of Vita games where the menu's are touch screen only. Killzone for example.

**Comment by CallmeBK** [comment]
Oh I see. Yeah I agree that notification is annoying.
